### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by repat** [stevegrunwell/time-constants#8]
Hi,

could you just remove the PHP version from the requirements in `composer.json` or at least allow PHP8:

`"php": "^7.1 | ^8.0",`

or

`"php": ">=7.1",`

A couple of `define()`s don't need PHP 7.1 ;)

Thanks!

**Comment by stevegrunwell** [comment]
Hi @repat,

My apologies, I must have missed this notification ::checks watch:: a year ago.

I actually was bit by this issue while working on upgrading an app to PHP 8.0 this evening, and have opened #9 to fix it.

Thank you for bringing this to my attention!
